add changes flexbox
idsintehittapa/my-miscarriage pull request #7
Opened 2020-10-20 13:43 UTC by carlacentenor

Hello 
I add my changes about flexbox

#3

2020-10-20 13:51 UTC, idsintehittapa requested changes

2020-10-20 13:51 UTC, idsintehittapa commented on code/mm_index.html
What did you change here? What I can see you deleted and added back the same code?

2020-10-20 13:51 UTC, idsintehittapa commented on code/mm_index.html
> +    <script src="mmscript.js"></script>
Same question - what did you change?
It looks like you deleted the block of code and then added it again.

This seems to be the case everywhere. Can you walk it through and explain the changes you made and how this is adding to the grid.

2020-10-20 14:32 UTC, carlacentenor commented on code/mm_index.html
Hello, I don't add changes here . Maybe the identation change for my code editor.

2020-10-20 14:38 UTC, idsintehittapa commented on code/mm_index.html
Ok, but I cannot find that you changed anything for this PR (maybe only the indentation everywhere?) - can you please show/tell me what you changed. Since I cannot really find any changes at all.

2020-10-20 14:41 UTC, idsintehittapa requested changes
Ok, so the only thing you seem to have changed is the indentation. I am unsure how this is related to updating the issue topic and why you did the PR. Care to share? :)

2020-10-20 14:43 UTC, carlacentenor commented on code/mm_index.html
> +    <script src="mmscript.js"></script>
I add these changes in CSS
**CSS***
` .img-container {
     box-sizing: border-box;
     width: 100%;
     display: flex;
     flex-wrap: wrap;
     justify-content: center;
     align-items: center;
     padding: 10px;
 }
 
 .img-container a {
     width: 45%;
     display: flex;
     justify-content: center;
     margin: 5px;
 }
 
 @media screen and (min-width: 768px) {
     .img-container a {
         width: 25%;
         display: flex;
         justify-content: center;
         margin: 20px 0 0 0;
     }
 }`

2020-10-20 14:48 UTC, carlacentenor commented on code/mm_index.html
I add these changes in CSS
**CSS***
` .img-container {
     box-sizing: border-box;
     width: 100%;
     display: flex;
     flex-wrap: wrap;
     justify-content: center;
     align-items: center;
     padding: 10px;
 }
 
 .img-container a {
     width: 45%;
     display: flex;
     justify-content: center;
     margin: 5px;
 }
 
 @media screen and (min-width: 768px) {
     .img-container a {
         width: 25%;
         display: flex;
         justify-content: center;
         margin: 20px 0 0 0;
     }
 }`

2020-10-20 14:53 UTC, carlacentenor commented
@idsintehittapa  Sorry for this problem, I only add changes in CSS
I hope these changes in css are ok 
:)

2020-10-21 08:37 UTC, idsintehittapa commented on code/mm_index.html
Ah cool!
Can you fix the indentation so it's not changed. 

Also change @media to
@media screen and (min-width: 768px) {
.img-container a {
width: 25%;
margin: 20px 0 0 0;
}
}`

Since you don't have to specify flex and justify-content again.
Then I can merge your PR :)

2020-10-27 09:34 UTC, idsintehittapa commented on code/mm_index.html
I'll be happy to approve your PR when you have fixed 

the indentation so it's not changed.

Also change @media to
@media screen and (min-width: 768px) {
.img-container a {
width: 25%;
margin: 20px 0 0 0;
}
}`

Can/will you have time to do it?

2020-10-27 14:30 UTC, carlacentenor commented on code/mm_index.html
@idsintehittapa  I add changes in CSS .
Please Review

2020-11-04 10:03 UTC, merged